spring:
  profiles:
    active: vault
  application.name: config-server
  cloud.config.server:
    vault:
      order: 1
      scheme: http
      host: 127.0.0.1
      port: 8200
      kvVersion: 2
      token: ${SPRING_CLOUD_CONFIG_TOKEN}
      default-key: config-repository
      authentication: TOKEN
    git:
      default-label: main
      uri: https://github.com/Dargor94/prom-path-config-repository
      username: ${config-repository.username}
      password: ${config-repository.password}
      clone-on-start: true
      order: 2
server.port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    region: default
    registryFetchIntervalSeconds: 5
logging:
  level:
    root: info