server.port: 8888
spring:
  application.name: config-server
  cloud.config.server.git:
    default-label: main
    uri: https://github.com/Dargor94/prom-path-config-repository
    clone-on-start: true