spring:
  application.name: config-server
  cloud.config.server.git:
    default-label: main
    uri: https://github.com/Dargor94/prom-path-config-repository
    clone-on-start: true
server.port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
    region: default
    registryFetchIntervalSeconds: 5
