apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: ghcr.io/dargor94/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: VAULT_TOKEN
              value: root
      imagePullSecrets:
        - name: regcred
